# Generated by Django 5.0 on 2024-01-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name="Character's first name")),
                ('lastname', models.CharField(max_length=30, verbose_name="Character's last name")),
                ('curr_time', models.IntegerField(verbose_name='Current time in story')),
                ('ability', models.CharField(max_length=30, verbose_name="Character's adapted ability (if applicable)")),
                ('role', models.CharField(max_length=20, verbose_name="Character's role")),
                ('description', models.CharField(max_length=300, verbose_name='Current description of character')),
                ('items', models.CharField(max_length=300, verbose_name='Current inventory of character')),
                ('relations', models.CharField(max_length=300, verbose_name='Current relations relevant to character in this timeframe')),
            ],
        ),
    ]
