# Generated by Django 5.0 on 2024-01-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('firstname', 'lastname', 'curr_time'), name='mock_pk'),
        ),
    ]
